mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('survey.urls')),
    path('admin/', admin.site.urls),
]

mysite/survey/urls.py
from django.urls import URLPattern, path
from . import views

app_name="survey"

urlpatterns = [
    path('', views.home, name="home"),
    path('questions/<int:cust_id>/<int:id>', views.handler, name="handler"), 
    path('questions', views.start, name="start"), 
    path('end', views.close, name='close')
]

mysite/survey/models.py
from django.db import models

# Create your models here.
class Customers(models.Model):
    cust_id = models.IntegerField()
    survey = models.BooleanField(default=False)

    def __str__(self):
        return self.cust_id

class Question(models.Model):
    text = models.TextField()

    def __str___(self):
        return self.text

class Answers(models.Model):
    ques = models.ForeignKey(Question, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customers, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return f"Customer {self.customer.cust_id}, Question {self.ques.text}, Answer {self.text}"

mysite/survey/views.py
from django.shortcuts import render, redirect, reverse
from .models import Question, Customers, Answers
from django.http import Http404
from django.views.decorators.csrf import csrf_exempt
import uuid, random

# Create your views here.

def home(request):
    return render(request, 'survey/index.html', context={})

@csrf_exempt
def handler(request,cust_id,id):
    ques_list = [question for question in Question.objects.all()] #will call the database only one time
    n = len(ques_list)
    if(n<=0):
        raise Http404("Please insert questions for survey")
    if(request.method == 'GET'):
        print(id)
        if(id<=0):
            id = 0
        else:
            id = id-1
    elif(request.method == 'POST'):
        if(id >= n-1):
            return render(request, 'survey/form.html', context={"question":ques_list[id], "cust_id":cust_id, "islast": True})
        if(id<n):
            #save the answer to database
            input = request.POST['ans'+str(id)]
            print(input)
            c= Customers.objects.get(cust_id=cust_id)
            q = Question.objects.get(pk=id)
            resp = Answers(customer=c, ques=q, text=input)
            resp.save()
            id = id+1
    return render(request, 'survey/form.html', context={"question":ques_list[id], "cust_id":cust_id})

@csrf_exempt
def start(request):
    #cust_id = str(uuid.uuid4())
    cust_id = 13
    c = Customers(cust_id=cust_id)
    c.save()
    return redirect(f'questions/{cust_id}/0')
    #return reverse('survey:handler', kwargs={'id':0, 'cust_id':cust_id})

def close(request):
    return render(request,'survey/close.html')

mysite/survey/templates/survey/close.html
<div>
    Thank you for your time
</div>

mysite/survey/templates/survey/form.html
<div id="parent-div">
<form action="#" method="post">
    {% csrf_token %}
    <label>{{ question.id }}. </label>
    <label>{{ question.text }}</label><br>
    <input type="text" name="ans{{ question.id }}"><br><br>
    <button 
        hx-get="{% url 'survey:handler' cust_id question.id %}" 
        hx-trigger="click"
        hx-target="#parent-div"
        hx-swap="outerHTML"
        type="submit" 
        name="Next" 
        value="submit">
        Previous
    </button>
    {% if islast %}
        <button
            hx-get="{% url 'survey:close' %}" 
            hx-trigger="click"
            hx-target="#parent-div"
            hx-swap="outerHTML"
            type="submit" 
            name="Previous" 
            value="submit">
            Submit
        </button>
    {% else %}
        <button
            hx-post="{% url 'survey:handler' cust_id question.id %}" 
            hx-trigger="click"
            hx-target="#parent-div"
            hx-swap="outerHTML"
            type="submit" 
            name="Previous" 
            value="submit">
            Next
        </button>
    {% endif %}
</form>
</div>

mysite/survey/templates/survey/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Survey</title>
    </head>
    <body>
        <div style="text-align:center;" >
            <div id="parent-div">
                <h1 >Welcome to the survey!</h1>
                <button
                hx-get="{% url 'survey:start' %}"
                hx-trigger="click" 
                hx-target="#parent-div"
                hx-swap="outerHTML"
                >
                START
                </button>
            </div>
        </div>
        <script src="https://unpkg.com/htmx.org@1.7.0" integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo" crossorigin="anonymous" defer></script>
        <!--{% load static %}
        <script src="{% static 'survey/htmx.min.js' %" defer></script>-->
    </body>
</html>